import os
a=open('/home/Python/files/testing.txt','w')
a.write('This is testeing file cretaing by using python \n')
a.close()
b=open('/home/Python/files/testing.txt','a')
b.write("\nPython is also simple language\npython is powerful language too\n")
b.close()
c=open('/home/Python/files/testing.txt','r')
x=c.read()
print(x)
print(open('/home/Python/files/testing.txt','r').read())
#########reading only one line############
d=open('/home/Python/files/testing.txt','r')
v=d.readlines()
print('length of text file',len(v))
f=open('/home/Python/files/testing.txt','r')
z=f.readline()
print(z[1])
print("Out put for my understanding:",v[:10])
e=print(z.split())
print(e)
print(open('/home/Python/files/testing.txt','r').readlines()[2])
